### ISSUE TITLE
Send Finalized form crashes app

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-collect#11]
@abbyad 

Current System settings: 
Android Froyo

OEM: 
Samsung Galaxy Tab. 
1. Download and install the Collect (demo) from 
   https://play.google.com/store/apps/details?id=org.medicmobile.collect.android.demo
2. Start the Collect (Demo) application. 
3. Select "Fill Blank Form", choose any forms and enter dummy data. 
4. Select "Send Finalized Form". HANGS AND APP CRASHES. (Over 10+ trials)

Filed by @ngamita

**Comment by abbyad** [comment]
This was created (and closed) here: https://github.com/medic/medic-collect/issues/1
