### ISSUE TITLE
Creating a build with updated flavor requires bumping medic-collect

### ISSUE THREAD

**Issue by abbyad** [medic/medic-collect#13]
When build a new Collect apk with a project's files we currently need to bump the medic-collect version, which is overkill since the only part that changes is the medic-projects files. The result is that we can have multiple build versions of the unbranded version with the exact same code. We should find a way to build medic-collect specifying the medic-collect and medic-project tags separately.

Additionally, it would be useful to specify the product flavor to build instead of always doing a build-all which is increasingly time consuming and creates APKs with the wrong credentials.

**Comment by alxndrsn** [comment]
built artifacts' version number should include the versions of both `medic-collect` and `medic-projects`.

**Comment by abbyad** [comment]
Are you saying this is already possible?

**Comment by alxndrsn** [comment]
No, that's an aim for this ticket.

**Comment by kennsippell** [comment]
Fixed in https://github.com/medic/medic-collect/commit/73bf9988c776902e368ea6ac4ad8f84dbbd146dd
