### ISSUE TITLE
Cannot install ODK Collect as well as Medic Collect

### ISSUE THREAD

**Issue by abbyad** [medic/medic-collect#14]
Since Medic Collect is derived from ODK Collect, the package name was not changed to be able to more easily incorporate upstream changes. This has the effect of not being able to install both ODK Collect and Medic Collect, which may be problematic if users are involved with different projects and need both.

To avoid package naming issues we are better off divorcing them now, because doing it later will cause issues for upgrading existing deployments.

Aside from the package name, to fully divorce the applications we should also make sure that they do not use the same filesystem directories.

**Comment by abbyad** [comment]
Additionally, to more easily incorporate upstream changes it would be nice to avoid having to change all `import org.odk.collect.android.R;` to `import org.medicmobile.collect.android.R;`

I have this working by remapping them with `org.odk.collect.android.R.java`:
```
package org.odk.collect.android;

public class R {
    public static org.medicmobile.collect.android.R.anim anim = new org.medicmobile.collect.android.R.anim();
    public static org.medicmobile.collect.android.R.array array = new org.medicmobile.collect.android.R.array();
    public static org.medicmobile.collect.android.R.attr attr = new org.medicmobile.collect.android.R.attr();
    public static org.medicmobile.collect.android.R.bool bool = new org.medicmobile.collect.android.R.bool();
    public static org.medicmobile.collect.android.R.drawable drawable = new org.medicmobile.collect.android.R.drawable();
    public static org.medicmobile.collect.android.R.id id = new org.medicmobile.collect.android.R.id();
    public static org.medicmobile.collect.android.R.layout layout = new org.medicmobile.collect.android.R.layout();
    public static org.medicmobile.collect.android.R.string string = new org.medicmobile.collect.android.R.string();
    public static org.medicmobile.collect.android.R.style style = new org.medicmobile.collect.android.R.style();
    public static org.medicmobile.collect.android.R.xml xml = new org.medicmobile.collect.android.R.xml();    
}
```

Is there a better way to do this?

**Comment by garethbowen** [comment]
This is the only way I can think of to do this. I would add a `@deprecated` annotation on the `class` and a `@deprecated` javadoc to explain why. That way people using the wrong `R` will be notified.
