### ISSUE TITLE
Allow specifying flavour when building on CI

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-collect#16]
Split from #13

**Comment by abbyad** [comment]
Specifying flavor would help for building a new flavor's APK. When medic-collect is updated we'd want to update all builds so it would be useful to also maintain the option to build all flavors.

**Comment by kennsippell** [comment]
Fixed via https://github.com/medic/medic-collect/commit/73bf9988c776902e368ea6ac4ad8f84dbbd146dd
