### ISSUE TITLE
Add support for switching bikram sambat datepicker on using form language

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-collect#21]
Instead of using the build switch https://github.com/medic/medic-collect/blob/master/build.gradle#L70, add support for using the form's current language as per https://github.com/opendatakit/collect/pull/1509/files#diff-c4569759abab98c20df2aa91fe129bc8R335

**Comment by kennsippell** [comment]
@ashish-medic @binokaryg Can you comment on the priority of this improvement? Do you think this will be necessary for webapp deployments in nepal this year?

**Comment by kennsippell** [comment]
Deprioritizing improvements to medic-collect.
