### ISSUE TITLE
Cannot manually send reports via Internet

### ISSUE THREAD

**Issue by abbyad** [medic/medic-collect#29]
Sending a finalized report via internet fails with a 401, even though credentials are in the app and automated sending of report succeeds.

**To Reproduce**
1. In General Settings turn auto-sending off
2. Complete a form, save as finalized
3. Go to Send Finalized Form
4. Select the report, and click `Send (Internet)`
5. If it is succeeds, repeat from step 2, but wait 10 minutes before moving to step 3.
6. See the failed submission with 401.

**Expected behavior**
It is expected to submit the message to the instance and show a "success" dialog box.

**Logs**
This is the relevant portion of the logs showing a failed submission:
```
2019-06-14 15:29:50.847 21581-22247/? W/InstanceUploaderTask: Status code on Head request: 403
2019-06-14 15:29:50.961 21581-22247/? D/Http Post Response:: HTTP/1.1 401 Unauthorized
```

**Screenshots**
![image](https://user-images.githubusercontent.com/789512/59937803-66245700-9421-11e9-8736-a68ee5d36ea3.png)

**Environment**
- Instance: map-pk.app, running 3.3.0
- Client platform: Nokia 5.1 running Android 8.0.0
- App: Collect 
- Version: `1.4.5.1132-standard`

**Additional context**
By debugging I found that the credentials are set with an automated send, but not a manual send. If I add a compatible version of [this code from `NetworkReceiver`](https://github.com/medic/medic-collect/blob/29ee3161b2337fd1f58a157c649c052b0f81fd64/src/org/odk/collect/android/receivers/NetworkReceiver.java#L154-L163) to [`instanceUploaderTask`](https://github.com/medic/medic-collect/blob/29ee3161b2337fd1f58a157c649c052b0f81fd64/src/org/odk/collect/android/tasks/InstanceUploaderTask.java#L867) then the report is sent successfully. It is not yet clear why this stopped working. I find it hard to believe that this never worked, and suspect something changed, perhaps in newer versions of Android which in an effort to save data or battery releases a thread/data which holds the WebUtils credentials. Worth noting that auth has been completely rewritten in ODK Collect since we have branched off, so we are looking for a quick fix -- otherwise we are better working off of the latest ODK Collect which is a big effort in itself.

Initially reported in https://github.com/medic/medic-projects/issues/6397#issuecomment-499457039

**Comment by benkags** [comment]
As mentioned in the linked issue, this will be a blocker for the CDC-MOHKE project set to deploy end of this July. The users using collect for this project aren't getting SMS facilitation and will mostly use internet for submission. Users will need the ability to save and edit later so we cannot use automatic submission.

cc @Maigua @derickl

**Comment by abbyad** [comment]
Users that need to save and edit later should not be "marking forms as finalized" until they are in fact finalized, meaning they could still use automatic submission. That said, we should still do the quick fix to resolve this.

@MaxDiz, can you see how we can bring this to a sooner release to get this done in time?

**Comment by garethbowen** [comment]
Given that the development work is done let's include this in 3.7.0.

Is this ready for AT @abbyad ?

**Comment by MaxDiz** [comment]
Hi @garethbowen This is a blocker for the Africa's Talking aggregator deployment. Unless there is temporary workaround, I think we'll need to include in 3.6.0.

**Comment by garethbowen** [comment]
@MaxDiz The change is in Collect so it's on its own release schedule, so I'm reluctant to hold up the 3.6.0 release and delay MUSO for this. We can get a new Collect release out soon.

**Comment by garethbowen** [comment]
Merged.

**Comment by garethbowen** [comment]
@benkags I've built a v1.4.7 with this fix: https://github.com/medic/medic-collect/releases/tag/v1.4.7 . Would you be able to test it out and make sure it works for you?

**Comment by benkags** [comment]
Thank you @garethbowen 

Tested this in the following steps and all looks ok.

1. In General Settings turn auto-sending off
2. Complete a form, save as finalized
3. Go to Send Finalized Form
4. First submission works as expected.
5. Wait for 20 mins and repeat from step 2. Works :clap:  

However, navigation is broken; arrows aren't showing. Swiping for navigation works though. See the screenshots below and if this is not related to this issue I can open a separate issue for it. 
![IMG_20190709_105339](https://user-images.githubusercontent.com/3006199/60871155-d9f49b00-a23a-11e9-923d-e1fae49eda43.jpg)
_Nokia 1 running Android 8.1.0_
![Screenshot_20190709-100858](https://user-images.githubusercontent.com/3006199/60871253-0b6d6680-a23b-11e9-874e-41c6fccbe4cd.jpg)
_Oneplus 5T running Android 9_

**Comment by garethbowen** [comment]
@benkags Could you try with version 1.4.6 and see if it happens there too?

**Comment by benkags** [comment]
Confirmed it's happening with v1.4.6 too. Tested with [medic-collect-v1.4.6-base-debug.apk](https://github.com/medic/medic-collect/releases/download/v1.4.6/medic-collect-v1.4.6-base-debug.apk) @garethbowen

**Comment by garethbowen** [comment]
@kennsippell You have some recent experience with collect - any idea what's going on here?

**Comment by abbyad** [comment]
Can you confirm what your navigation settings are? In the General Settings, see the Navigation option

![Screenshot_20190710-082117](https://user-images.githubusercontent.com/789512/60968831-0b796f00-a2ec-11e9-99cb-0f6a81e958ca.png)

The other issue that I see in the screenshots is that `@+string/backup` and `@+string/advance` are showing instead of the proper label. The labels are present in the strings.xml, so not quite sure yet why it isn't using it in the build.

**Comment by benkags** [comment]
Thanks @abbyad, that adds the navigation buttons but does not fix display of proper labels.

**Comment by abbyad** [comment]
I've created a fix for the labels which works locally.

@garethbowen, when it passes review please merge and create the new build for @benkags to test. Thanks!

**Comment by garethbowen** [comment]
@benkags v1.4.8 is built and ready for testing.

**Comment by benkags** [comment]
Thanks @garethbowen @abbyad . This is fixed and is now working.

**Comment by abbyad** [comment]
~Closing now that this has been fixed and released in [v1.4.8](https://github.com/medic/medic-collect/releases/tag/v1.4.8).~

**Comment by abbyad** [comment]
Although this is already included in [v1.4.8](https://github.com/medic/medic-collect/releases/tag/v1.4.8), it is still pre-release, so moved to _In AT_ for it to be properly acceptance and release tested.

**Comment by newtewt** [comment]
I'm getting a 404 when I try to send to gamma.dev. 

![Screenshot_20190805-124610](https://user-images.githubusercontent.com/10531066/62481014-49e53b00-b77f-11e9-8306-2974ecd13d0a.png)

**Comment by abbyad** [comment]
Can you try again with `/api/v1/records` as the endpoint? You can change it via `Admin Settings` > `General Settings` > `Configure platform settings` > `Submission path`

**Comment by newtewt** [comment]
I'm manually sending and automatically sending just fine.
