### ISSUE TITLE
Send reports to medic-webapp using API

### ISSUE THREAD

**Issue by abbyad** [medic/medic-collect#3]
Currently a 500 error is received when sending reports to `/api/v1/records` whereas `/add` works.

Looking at the couch logs, it seems to be a 404 though (log posted privately).

Aside from any medic-webapp issues, it seems as though the headers should be fixed in Collect as well, as per the [API doc](https://github.com/medic/medic-api/blob/develop/API_v1.md#records)

**Comment by garethbowen** [comment]
It looks like their version of api doesn't have a handler for `/api/v1/records` so that request is just being proxied through to couch.

**Comment by abbyad** [comment]
Ok, so it sounds like `/api/v1/records` is not in v4.8 then. Thanks @garethbowen.

**Comment by mandric** [comment]
Hrm it does seem to be in master though. https://github.com/medic/medic-api/blob/master/API_v1.md

**Comment by mandric** [comment]
I just created this record on 0.4.8 using /api/v1/records:

https://demo.app.medicmobile.org/medic/_design/medic/_rewrite#/reports/b00cd83d397e0e8a98fb250f427d6f88

```
curl -XPOST -u admin https://demo.app.medicmobile.org/api/v1/records  -d 'message=J1!ISSN!d#2015-08-01#y#3#m#8#q1#100#q2#100#q3#100#q4#100#q5#100#q6#100#q7#100#q8#100#q9#100#m_st#2015-08-11T11:55:06.976+03#m_et#2015-08-11T11:56:08.277+03#m_t#2015-08-11#m_d#imei:358675056680058#m_s#imsi:639029550784145#m_i#uuid:7794e4cf-5fa6-4838-ae9e-5b52b452b57b#&from=+254705087291'
```

**Comment by mandric** [comment]
According to changes log was added in 0.4.5. https://github.com/medic/medic-webapp/blob/develop/Changes.md

**Comment by abbyad** [comment]
I am guessing that `Initial support for messages` is part of the issue... I will look at debugging/fixing the headers from Collect to use this.

**Comment by abbyad** [comment]
Fixed with https://github.com/medic/medic-collect/commit/8e27915ebc3f9e832e2d1e4badeb62fb6a0ca17d
