### ISSUE TITLE
Cannot assemble release builds

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-collect#30]
Steps to Reproduce:
`./gradlew assembleDemoRelease`

`Execution failed for task ':lintVitalDemoRelease'.` along with heaps and heaps of statements like `Could not find com.google.code.gson:gson:2.8.0.`.  Can build debug builds without issue.

**Comment by garethbowen** [comment]
@kennsippell Does this mean we can't ship updated apks, or that everyone has to run a debug version? I'm trying to work out what priority this should have...

**Comment by kennsippell** [comment]
@garethbowen From what I can tell, we have been building and distributing debug versions of the collect app for quite some time. The automated build (#28) will streamline the existing process, but that PR assembles and uploads debug builds only. Given that this is a long-standing practice without user impact, I'm also unsure how to prioritise this.

**Comment by kennsippell** [comment]
Seems we have been living with debug builds in production for some time. Deprioritizing investments in collect. Please re-activate if deemed critical to your project.
