### ISSUE TITLE
Collect is building against old versions of the sdks. These need to be updated. 

### ISSUE THREAD

**Issue by newtewt** [medic/medic-collect#32]
If we are ever allowed to upload collect to the play store we'll need to update the sdk versions.  They are currently very old.  

API level requirement | Starting date
-- | --
Android 8.0 (API level 26) | August 1, 2018: Required for new appsNovember 1, 2018: Required for app updates
Android 9 (API level 28) | August 1, 2019: Required for new appsNovember 1, 2019: Required for app updates

` <uses-sdk android:minSdkVersion="7" android:targetSdkVersion="8" />` 

Article detailing the version requirements.

https://developer.android.com/distribute/best-practices/develop/target-sdk

and the play store requirements

https://support.google.com/googleplay/android-developer/answer/113469#targetsdk

**Comment by MaxDiz** [comment]
may be related to #36
