### ISSUE TITLE
Investigate replacing Medic Collect with mainline ODK Collect app

### ISSUE THREAD

**Issue by abbyad** [medic/medic-collect#35]
Medic Collect was forked from [ODK Collect](https://github.com/opendatakit/collect) in January 2015, over four and a half years ago, and hasn't been rebased since then (#23).  Given that Android is a constantly evolving, we occasionally discover bugs, and that Play store regularly introduces new requirements (eg 64 bit, deprecates SDKs), we are forced to periodically update Medic Collect. As would be expected, updating medic-collect is getting harder to do and more time consuming to do on an ever aging base. 

Given that our mobile app for CHW is used for all patient centered care, we haven't had any major feature development on Medic Collect since the initial push, which focused on some key functionality for quick data collection. We may be able to now replace Medic Collect with ODK Collect for our deployments that need it for quick surveys and data collection. A list of the features we've implemented in Collect are listed at the end of this comment along with their current state. The key feature we'd need is SMS sending of finalized forms.

As a first step we should investigate if we can reintroduce the SMS functionality in ODK Collect in a way that would be acceptable to the ODK community, as per https://github.com/opendatakit/collect/issues/2934#issuecomment-505919405. If so, then we can reintroduce the other features into the mainstream app, or worst case re-implement them in our own updated fork in a way that will make it easier to stay updated with upstream. If we can't reintroduce the SMS functionality into the mainstream app we can then consider maintaining a fork with the SMS features applied in a way that can be easily maintained, otherwise maintain medic-collect in its current form until we decide we can't support it any longer. Given that that is not an ideal outcome, we should investigate using ODK Collect first.

### 1. **Option to Send Finalized Form using SMS**
_Our users often do not have a reliable data connection, if at all, so this was a major reason why we hadnt used Collect previously. We added "Send via SMS" support in Collect, which also needed a fix in org.javarosa.model.xform.SMSSerializingVisitor._

Key feature for deployments doing simple surveys or data collection (not patient-centered) and want to send data to send to [medic](https://github.com/medic/medic). Sending via SMS was introduced into ODK Collect [v1.16](https://forum.opendatakit.org/t/odk-collect-v1-16/14157) ([documentation](https://docs.opendatakit.org/collect-sms-submissions/)), but [removed when Play store restricted the SEND_SMS permission](https://forum.opendatakit.org/t/removal-of-sending-submissions-via-sms-in-collect/17973). If we find a way to re-enable SMS as part of https://github.com/opendatakit/collect/issues/2934, we could consider replacing Medic Collect with ODK Collect, or at least forking from a much newer ODK Collect to take advantage of all the updates since 2015.

### 2. **Deploy with Built-In Forms**
_As our users may only be sending the forms via SMS, they may not have any data connection. As such, they are not necessarily able to download new forms, so we include the forms in the build's assets and draw them from there on first load. This is also very useful to decrease the time it takes to deploy on a large number of devices since it doesn't require manually copying files over to the /odk/forms directory._

Potentially useful, could be re-implemented if needed. Otherwise we can streamline the uploading of the forms during the side-loading of the app. @derickl, @@mukesh2006, how important is this feature, and is Collect still usable by projects without this feature?

### 3. **Deploy with Built-In Settings**
_Nafundi had added the feature to copy over settings to a device using the collect.settings file. To avoid this manual step, we put the settings into the build and use it on first load. From the admin menu you can also "reset to default settings" to make resetting phones in the field easier. Aside from the collect.settings file, we can also use a JSON version of the settings to make it easier to edit before including the settings in a build._

Potentially useful, and like built-in forms this could be handled manually. @derickl, @mukesh2006, would be good to get your input on this too.

### 4. **Android Notifications**
_In order to remind users to submit reports we added Android notifications to Collect. The notifications and their content are completely configurable in the preferences using a cron-like schedule._

Used for two projects with weekly/monthly service reporting that ended several years ago, and no longer used for existing deployments. Could be removed and if needed again in the future could be re-implemented with modern techniques since notifications have changed in Android since.

### 5. **Quick select for Cascading Selects**
_After noticing that `appearance="quick"` was not working for cascading selects we added a new widget to be able to handle this field type._

May not be an issue with the updated ODK Collect. If it is, and this is still needed should be updated in mainstream ODK Collect.

### 6. **Send SMS content as payload when submitting report via internet** 

_Option to send the SMS version of a completed form as the payload when submitting report via internet. This was done to reuse an existing endpoint in the Medic app._

Instead of re-implementing this feature, to work with ODK Collect via the internet we could add an endpoint in Medic to [receive OpenRosa XForm submissions](https://docs.opendatakit.org/openrosa-form-submission/). This would need to be spawned off as a separate issue in [medic/medic](https://github.com/medic/medic).

[**edit**: feature 6 included after initial posting]

**Comment by derickl** [comment]
@abbyad feature 2 & 3 are important. 
2) makes it easy to deploy and update forms (without recalling devices). 
3) makes it easy (and almost error-free) to deploy settings.

If we can, we should incorporate both capabilities unless the cost outweighs the benefits. At the very minimum, we should have 2)

**Comment by abbyad** [comment]
Thanks for the feedback @derickl.

To better understand how you would use the feature, could you describe how Feature 2 makes it easy to "update forms (without recalling devices)"? This feature works when you first install the app on devices -- are apps for some deployments installed remotely?

**Comment by abbyad** [comment]
Also worth noting that Medic can accept reports from Medic Collect sent via the internet, but not from ODK Collect, even if it has the SMS features. This is because Medic Collect has the option to send the SMS content as the payload rather than the XForm XML. I will add that to the original post to update the consolidated features list.

This means that we couldn't immediately use ODK Collect for our projects as is, even with the SMS feature re-enabled, since most deployments want the option of sending via SMS or internet. That helps to flesh out was is needed as part of a switch to ODK Collect. 

**The focus of this issue is now to figure out what is needed from the ODK Community to re-enable the SMS functionality.**

Once a path forward is known, we can spawn off remaining work into new issues to be scheduled in future releases.

**Comment by abbyad** [comment]
There is relevant conversation about sending SMS via a side-loaded app in https://github.com/medic/medic-android/issues/71#issuecomment-531257454. If ODK Collect moves towards supporting this app too it would push this issue forward too.

**Comment by abbyad** [comment]
Closing this issue now that ODK Collect [has removed its SMS functionality](https://github.com/getodk/collect/issues/2934), as the plan to replace Medic Collect with ODK Collect is no longer realistic.

Another possibility is to replace Medic Collect with CHT applications, and we can open an issue for that when we want to investigate it.
