### ISSUE TITLE
Update to target latest Android SDK

### ISSUE THREAD

**Issue by derickl** [medic/medic-collect#36]
On opening the app for the first time on a device with Android 9 (Nokia 2.1, July 2019 Patch), I get the following notification:

![Screenshot_20190806-113715](https://user-images.githubusercontent.com/83162/62526140-54680900-b841-11e9-8b7d-90e0954ea593.png)

**Comment by kennsippell** [comment]
@derickl Do you know of any bugs indicating that it isn't working properly? My understanding is that medic-collect is no longer supported and maybe this sort of issue can remain unfixed. Please re-activate if you disagree.

**Comment by derickl** [comment]
No known bugs
