### ISSUE TITLE
Validate gateway number when entered

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-collect#5]
Currently we are validating gateway number when sending SMS, but this takes enough time to make the sending appear slower than it needs to be. It would be preferable to validate the gateway number when it is entered.

Filed by @abbyad

**Comment by prabinrs** [comment]
short code number is not accepted as the gateway number

**Comment by abbyad** [comment]
Good point - it is hard to validate for long phone numbers and allow short codes. In what format is the short code you want to use?

**Comment by prabinrs** [comment]
these are 4 digit numbers provided by SMS VAS like 4546 (with country code +9774546).

**Comment by alxndrsn** [comment]
@prabinrs do the shortcode numbers work with a country code?

**Comment by prabinrs** [comment]
Yup, It is working

**Comment by alxndrsn** [comment]
Interesting!  Have you tested it internationally, or just in the country which the shortcode & country code refer to?

**Comment by prabinrs** [comment]
I haven't tested internationally but from within the country it works with and without country code.

**Comment by kennsippell** [comment]
Deprioritizing collect work. Please re-activiate if this would be useful for you!
